// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Addr } from "./Addr";
import type { Group } from "./Group";

export type Address = { "List": Array<Addr> } | { "Group": Array<Group> };
