// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An RFC2047 Content-Type or RFC2183 Content-Disposition MIME header field.
 */
export type ContentType = { c_type: string, c_subtype: string | null, attributes: Array<[string, string]> | null, };
