// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An RFC5322 datetime.
 */
export type DateTime = { year: number, month: number, day: number, hour: number, minute: number, second: number, tz_before_gmt: boolean, tz_hour: number, tz_minute: number, };
