// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeaderName } from "./HeaderName";
import type { HeaderValue } from "./HeaderValue";

/**
 * A message header.
 */
export type Header = { name: HeaderName, value: HeaderValue, offset_field: number, offset_start: number, offset_end: number, };
