// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { ContentType } from "./ContentType";
import type { DateTime } from "./DateTime";
import type { Received } from "./Received";

/**
 * Parsed header value.
 */
export type HeaderValue = { "Address": Address } | { "Text": string } | { "TextList": Array<string> } | { "DateTime": DateTime } | { "ContentType": ContentType } | { "Received": Received } | "Empty";
