// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessagePart } from "./MessagePart";

/**
 * An RFC5322/RFC822 message.
 */
export type Message = { html_body: Array<number>, text_body: Array<number>, attachments: Array<number>, parts: Array<MessagePart>, };
