// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Header } from "./Header";
import type { PartType } from "./PartType";

/**
 * MIME Message Part
 */
export type MessagePart = { headers: Array<Header>, is_encoding_problem: boolean, body: PartType, offset_header: number, offset_body: number, offset_end: number, };
