// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Protocol = "SMTP" | "ESMTP" | "ESMTPA" | "ESMTPS" | "ESMTPSA" | "LMTP" | "LMTPA" | "LMTPS" | "LMTPSA" | "MMS" | "UTF8SMTP" | "UTF8SMTPA" | "UTF8SMTPS" | "UTF8SMTPSA" | "UTF8LMTP" | "UTF8LMTPA" | "UTF8LMTPS" | "UTF8LMTPSA" | "HTTP" | "HTTPS" | "IMAP" | "POP3" | "Local";
