// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "./DateTime";
import type { Greeting } from "./Greeting";
import type { Host } from "./Host";
import type { Protocol } from "./Protocol";
import type { TlsVersion } from "./TlsVersion";

export type Received = { from: Host | null, from_ip: string | null, from_iprev: string | null, by: Host | null, for_: string | null, with: Protocol | null, tls_version: TlsVersion | null, tls_cipher: string | null, id: string | null, ident: string | null, helo: Host | null, helo_cmd: Greeting | null, via: string | null, date: DateTime | null, };
