// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An RFC5322 or RFC2369 internet address.
 */
export type Addr = { 
/**
 * The address name including comments
 */
name: string | null, 
/**
 * An e-mail address (RFC5322/RFC2369) or URL (RFC2369)
 */
address: string | null, };
