// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RfcHeader } from "./RfcHeader";

export type HeaderName = { "Rfc": RfcHeader } | { "Other": string };
