// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Addr } from "./Addr";
import type { ContentType } from "./ContentType";
import type { DateTime } from "./DateTime";
import type { Group } from "./Group";

/**
 * Parsed header value.
 */
export type HeaderValue = { "Address": Addr } | { "AddressList": Array<Addr> } | { "Group": Group } | { "GroupList": Array<Group> } | { "Text": string } | { "TextList": Array<string> } | { "DateTime": DateTime } | { "ContentType": ContentType } | "Empty";
