// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

/**
 * A text, binary or nested e-mail MIME message part.
 *
 * - Text: Any text/* part
 * - Binary: Any other part type that is not text.
 * - Message: Nested RFC5322 message.
 * - MultiPart: Multipart part.
 *
 */
export type PartType = { "Text": string } | { "Html": string } | { "Binary": Array<number> } | { "InlineBinary": Array<number> } | { "Message": Message } | { "Multipart": Array<number> };
