// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A header field
 */
export type RfcHeader = "subject" | "from" | "to" | "cc" | "date" | "bcc" | "reply_to" | "sender" | "comments" | "in_reply_to" | "keywords" | "received" | "message_id" | "references" | "return_path" | "mime_version" | "content_description" | "content_id" | "content_language" | "content_location" | "content_transfer_encoding" | "content_type" | "content_disposition" | "resent_to" | "resent_from" | "resent_bcc" | "resent_cc" | "resent_sender" | "resent_date" | "resent_message_id" | "list_archive" | "list_help" | "list_id" | "list_owner" | "list_post" | "list_subscribe" | "list_unsubscribe";
