// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TlsVersion = "SSLv2" | "SSLv3" | "TLSv1_0" | "TLSv1_1" | "TLSv1_2" | "TLSv1_3" | "DTLSv1_0" | "DTLSv1_2" | "DTLSv1_3";
